#https://s3.amazonaws.com/ssm-artifacts/blog/2017/replacing-a-bastion-host-with-amazon-ec2-systems-manager/ssm-no-bastion.template

AWSTemplateFormatVersion: 2010-09-09        
Description: Nested Stack SG exercise

Parameters:
    VpcIdParam:
        Description: Create SG in this VpcId
        Type: AWS::EC2::VPC::Id
        

Resources:
    DevSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Dev Apps SG
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: 0.0.0.0/0 
                - IpProtocol: tcp
                  FromPort: 8080
                  ToPort: 8080
                  CidrIp: 0.0.0.0/0                   
            VpcId: !Ref VpcIdParam
        
Outputs:
    DevSGGroupId:
        Description: Dev Security Group
        Value: !Ref DevSecurityGroup