Parameters:
    SecurityGroupDescription:
        Description: Security Group Description
        Type: String
        
Resources:
    MyInstance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: us-east-1b
            ImageId: ami-0a887e401f7654935
            InstanceType: "t2.micro"
            "NetworkInterfaces": [
                    {
                        "AssociatePublicIpAddress": true,
                        "DeviceIndex": 0,
                        "SubnetId": "subnet-05ae0f741d6337541",
                        "GroupSet": [
                            {
                                "Ref": "MySecGroup"
                            }
                        ]
                    }
                ]
            BlockDeviceMappings:
            -
                DeviceName: /dev/sda1
                Ebs:
                    VolumeSize: 5   
    MySecGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Security group for AWS"
            VpcId: vpc-00331ca56ca0af8a7
            SecurityGroupIngress: [
                {
                    "FromPort": 22,
                    "ToPort": 22,
                    "IpProtocol": "tcp",
                    "CidrIp": "157.50.37.239/32"
                },
                {
                    "FromPort": 80,
                    "ToPort": 80,
                    "IpProtocol": "tcp",
                    "CidrIp": "0.0.0.0/0"
                }
            ]
# how to create ALB and place them in VpcId: vpc-00331ca56ca0af8a7
    MyELB:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Subnets: 
            -
                subnet-05ae0f741d6337541
                subnet-0d71a7db54d4f178e
              
              