---
Resources:
    MyInstance:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: us-east-1b
            ImageId: ami-0a887e401f7654935
            InstanceType: "t2.micro"
            "NetworkInterfaces": [
                    {
                        "AssociatePublicIpAddress": true,
                        "DeviceIndex": 0,
                        "SubnetId": "subnet-05ae0f741d6337541",
                    }
                ]

