---
Resources:
    MyInstance:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Security group for AWS"
            VpcId: vpc-00331ca56ca0af8a7
            SecurityGroupIngress: [
                {
                    "FromPort": 22,
                    "ToPort": 22,
                    "IpProtocol": "tcp",
                    "CidrIp": "157.50.37.239/32"
                }
            ]
        
            
            
