AWSTemplateFormatVersion: 2010-09-09
Description: Using Import value exported from previous exercise

Parameters:
    MyKeyName:
        Description: "Select the key name"
        Type: AWS::EC2::KeyPair::KeyName
    MyEnvironmentName:
        Description: "Selct the Environment"
        Type: String
        Default: "Dev"
        AllowedValues:
            - Dev
            - Prod
        ConstraintDescription: must be Dev or Prod
Mappings:
    MyRegionMap:
        us-east-1:
            HVM64: ami-0a887e401f7654935
        us-east-2:
            HVM64: ami-0e38b48473ea57778
        us-west-1:
            HVM64: ami-01c94064639c71719
        us-west-2:
            HVM64: ami-0e8c04af2729ff1bb
    MyEnvironmentMap:
        Dev:
            InstanceType: t2.micro
        Prod:
            InstanceType: t2.small    
Conditions:
    IfRegionUseKeyName: !Or [!Equals [!Ref 'AWS::Region',us-east-1],!Equals [!Ref 'AWS::Region',us-west-1]]
Resources:
    MyEc2Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !FindInMap
                - MyRegionMap
                - !Ref 'AWS::Region'
                - HVM64
            InstanceType: !FindInMap
                - MyEnvironmentMap
                - !Ref MyEnvironmentName
                - InstanceType
            KeyName: !If [IfRegionUseKeyName,awssolutions-key,awssolutions-2-key]
            SecurityGroups: 
                - !ImportValue MyDevEnvGlobalSGVal
            AvailabilityZone: !ImportValue Stack-1-InstanceAz
    MyDevEnvSecurityGroup:
        Type: AWS::EC2::SecurityGroup
##        Condition: CreateDevSecurityGroup
        Properties:
            GroupDescription: My Dev Env SG
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

Outputs:
    MyInstanceId:
        Description: My Instance Id
        Value: !Ref MyEc2Instance                  
    MyDNSName:
        Description: My Public DNS Name
        Value: !GetAtt MyEc2Instance.PublicDnsName
    MyDevEnvGlobalSG:
        Description: My Dev Env Global SG
        Value: !Ref MyDevEnvSecurityGroup
     