AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
    MyKeyName:
        Description: "Select the key name"
        Type: AWS::EC2::KeyPair::KeyName
        

Resources:
    CFT1Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-0a887e401f7654935
            InstanceType: t2.micro
            KeyName: !Ref MyKeyName
            SecurityGroups: 
                - default
                - !Ref SSHSecurityGroup
    SSHSecurityGroup:
        Type: AWS::EC2::SecurityGroup   
        Properties: 
            GroupDescription: "My new SSH SG"
            SecurityGroupIngress:
                -   IpProtocol: tcp
                    FromPort: 22
                    ToPort: 22
                    CidrIp: 0.0.0.0/0
                -   IpProtocol: tcp
                    FromPort: 80
                    ToPort: 80
                    CidrIp: 0.0.0.0/0
    CFT1EIP:
        Type: AWS::EC2::EIP
        Properties:
            InstanceId: !Ref CFT1Instance