AWSTemplateFormatVersion: 2010-09-09
Description: Mapping Demo.

Mappings:
    MyRegionMap:
        us-east-1:
            HVM64: ami-0a887e401f7654935
        us-east-2:
            HVM64: ami-0e38b48473ea57778
        us-west-1:
            HVM64: ami-01c94064639c71719
        us-west-2:
            HVM64: ami-0e8c04af2729ff1bb
        
Resources:
    CFT1Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !FindInMap
                - MyRegionMap
                - !Ref 'AWS::Region'
                - HVM64
            InstanceType: t2.micro
            KeyName: awssolutions-key
            SecurityGroups: 
                - default
